"""
Self-service two-factor authentication (TOTP) setup/disable views.

These are session-authenticated AJAX endpoints for the GUI (like
``ProtocolSaveAPIView``/``ExaminationSaveAPIView``), not DRF token-authenticated
API endpoints — the project's DRF ``DEFAULT_AUTHENTICATION_CLASSES`` only
recognizes Bearer/Token headers, not the Django session cookie set by
``auth_login()``.
"""

import json
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView

from .models import TOTPDevice
from .twofactor import generate_secret, provisioning_uri, qr_code_data_uri, verify_code

logger = logging.getLogger(__name__)


class SecuritySettingsView(LoginRequiredMixin, TemplateView):
    """Self-service page where a user manages their own 2FA and views their
    Data Classification Declaration."""
    template_name = 'uploads/security_settings.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        device = TOTPDevice.objects.filter(user=self.request.user).first()
        ctx['totp_enabled'] = bool(device and device.confirmed)
        ctx['profile'] = getattr(self.request.user, 'profile', None)
        return ctx


class TOTPSetupInitiateView(LoginRequiredMixin, View):
    """AJAX endpoint: generate a new (unconfirmed) TOTP secret and its QR code."""
    login_url = '/login/'

    def post(self, request, *args, **kwargs):
        secret = generate_secret()
        TOTPDevice.objects.update_or_create(
            user=request.user,
            defaults={'secret': secret, 'confirmed': False, 'confirmed_at': None},
        )
        uri = provisioning_uri(request.user, secret)
        return JsonResponse({
            'secret': secret,
            'qr_data_uri': qr_code_data_uri(uri),
        })


class TOTPSetupConfirmView(LoginRequiredMixin, View):
    """AJAX endpoint: confirm the pending secret generated by TOTPSetupInitiateView."""
    login_url = '/login/'

    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
        except (json.JSONDecodeError, ValueError):
            return JsonResponse({'error': 'Invalid JSON'}, status=400)

        code = str(data.get('code', '')).strip()
        device = TOTPDevice.objects.filter(user=request.user, confirmed=False).first()

        if not device:
            return JsonResponse(
                {'error': 'No pending 2FA setup found. Start setup again.'}, status=400,
            )

        if not code or not verify_code(device.secret, code):
            return JsonResponse(
                {'error': 'Invalid code. Please try again.'}, status=400,
            )

        device.confirmed = True
        device.confirmed_at = timezone.now()
        device.save(update_fields=['confirmed', 'confirmed_at'])

        logger.info(f"2FA enabled for user: {request.user.username}")
        return JsonResponse({'message': 'Two-factor authentication enabled.'})
