--
-- PostgreSQL database dump
--

\restrict BIpTuvVNmzGFPMugSgYpeTYfLYwBdNv4jiDblPOFDzrDFHFQZSdh1C45lXGbCr5

-- Dumped from database version 15.16
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: uploads_annotation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_annotation (
    id uuid NOT NULL,
    orthanc_instance_id character varying(256) NOT NULL,
    annotation_uid character varying(256) NOT NULL,
    annotator_id character varying(128) NOT NULL,
    annotation_date date,
    type character varying(16) NOT NULL,
    label character varying(256) NOT NULL,
    annotation_data jsonb,
    annotation_file character varying(100),
    created_at timestamp with time zone NOT NULL,
    study_mapping_id uuid NOT NULL
);


ALTER TABLE public.uploads_annotation OWNER TO postgres;

--
-- Name: uploads_auditlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_auditlog (
    id uuid NOT NULL,
    event_type character varying(64) NOT NULL,
    actor_id character varying(128) NOT NULL,
    detail jsonb,
    occurred_at timestamp with time zone NOT NULL,
    upload_job_id uuid
);


ALTER TABLE public.uploads_auditlog OWNER TO postgres;

--
-- Name: uploads_chunkedupload; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_chunkedupload (
    id uuid NOT NULL,
    uploader_id character varying(128) NOT NULL,
    status character varying(16) NOT NULL,
    filename character varying(512) NOT NULL,
    total_size bigint NOT NULL,
    total_chunks integer NOT NULL,
    uploaded_chunks integer NOT NULL,
    chunk_size integer NOT NULL,
    file_hash character varying(128),
    temp_dir character varying(512) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    expires_at timestamp with time zone,
    CONSTRAINT uploads_chunkedupload_chunk_size_check CHECK ((chunk_size >= 0)),
    CONSTRAINT uploads_chunkedupload_total_chunks_check CHECK ((total_chunks >= 0)),
    CONSTRAINT uploads_chunkedupload_uploaded_chunks_check CHECK ((uploaded_chunks >= 0))
);


ALTER TABLE public.uploads_chunkedupload OWNER TO postgres;

--
-- Name: uploads_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_image (
    id uuid NOT NULL,
    filename character varying(256) NOT NULL,
    orthanc_instance_id character varying(64),
    sop_instance_uid character varying(256),
    created_at timestamp with time zone NOT NULL,
    study_mapping_id uuid NOT NULL
);


ALTER TABLE public.uploads_image OWNER TO postgres;

--
-- Name: uploads_patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_patient (
    id uuid NOT NULL,
    pseudo_id character varying(64) NOT NULL,
    sex character varying(1),
    age_at_first_acquisition integer,
    cohort_tag character varying(128),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uploads_patient_age_at_first_acquisition_check CHECK ((age_at_first_acquisition >= 0))
);


ALTER TABLE public.uploads_patient OWNER TO postgres;

--
-- Name: uploads_studymapping; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_studymapping (
    id uuid NOT NULL,
    pseudo_study_uid character varying(256) NOT NULL,
    orthanc_study_id character varying(64),
    acquisition_date date NOT NULL,
    clinical_indication text NOT NULL,
    pathology_labels jsonb NOT NULL,
    contrast_used boolean NOT NULL,
    contrast_agent character varying(128),
    source_institution character varying(128),
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    patient_id uuid NOT NULL,
    upload_job_id uuid
);


ALTER TABLE public.uploads_studymapping OWNER TO postgres;

--
-- Name: uploads_uploadchunk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_uploadchunk (
    id uuid NOT NULL,
    chunk_number integer NOT NULL,
    chunk_size bigint NOT NULL,
    chunk_hash character varying(128) NOT NULL,
    file_path character varying(512) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    verified boolean NOT NULL,
    chunked_upload_id uuid NOT NULL,
    chunk_crc32 character varying(8),
    verification_status character varying(20) NOT NULL,
    verification_error text,
    verification_timestamp timestamp with time zone,
    CONSTRAINT uploads_uploadchunk_chunk_number_check CHECK ((chunk_number >= 0))
);


ALTER TABLE public.uploads_uploadchunk OWNER TO postgres;

--
-- Name: uploads_uploadjob; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uploads_uploadjob (
    id uuid NOT NULL,
    uploader_id character varying(128) NOT NULL,
    status character varying(16) NOT NULL,
    tar_temp_path character varying(512) NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    manifest_raw jsonb,
    error_report jsonb,
    anonymization_report jsonb
);


ALTER TABLE public.uploads_uploadjob OWNER TO postgres;

--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: uploads_annotation uploads_annotation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_annotation
    ADD CONSTRAINT uploads_annotation_pkey PRIMARY KEY (id);


--
-- Name: uploads_auditlog uploads_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_auditlog
    ADD CONSTRAINT uploads_auditlog_pkey PRIMARY KEY (id);


--
-- Name: uploads_chunkedupload uploads_chunkedupload_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_chunkedupload
    ADD CONSTRAINT uploads_chunkedupload_pkey PRIMARY KEY (id);


--
-- Name: uploads_image uploads_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_image
    ADD CONSTRAINT uploads_image_pkey PRIMARY KEY (id);


--
-- Name: uploads_patient uploads_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_patient
    ADD CONSTRAINT uploads_patient_pkey PRIMARY KEY (id);


--
-- Name: uploads_patient uploads_patient_pseudo_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_patient
    ADD CONSTRAINT uploads_patient_pseudo_id_key UNIQUE (pseudo_id);


--
-- Name: uploads_studymapping uploads_studymapping_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_studymapping
    ADD CONSTRAINT uploads_studymapping_pkey PRIMARY KEY (id);


--
-- Name: uploads_studymapping uploads_studymapping_pseudo_study_uid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_studymapping
    ADD CONSTRAINT uploads_studymapping_pseudo_study_uid_key UNIQUE (pseudo_study_uid);


--
-- Name: uploads_uploadchunk uploads_uploadchunk_chunked_upload_id_chunk__0c80c591_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_uploadchunk
    ADD CONSTRAINT uploads_uploadchunk_chunked_upload_id_chunk__0c80c591_uniq UNIQUE (chunked_upload_id, chunk_number);


--
-- Name: uploads_uploadchunk uploads_uploadchunk_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_uploadchunk
    ADD CONSTRAINT uploads_uploadchunk_pkey PRIMARY KEY (id);


--
-- Name: uploads_uploadjob uploads_uploadjob_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_uploadjob
    ADD CONSTRAINT uploads_uploadjob_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: uploads_ann_annotat_47d4ff_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ann_annotat_47d4ff_idx ON public.uploads_annotation USING btree (annotation_uid);


--
-- Name: uploads_ann_annotat_ffc9ff_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ann_annotat_ffc9ff_idx ON public.uploads_annotation USING btree (annotator_id);


--
-- Name: uploads_ann_orthanc_e14856_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ann_orthanc_e14856_idx ON public.uploads_annotation USING btree (orthanc_instance_id);


--
-- Name: uploads_ann_study_m_18f71b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ann_study_m_18f71b_idx ON public.uploads_annotation USING btree (study_mapping_id);


--
-- Name: uploads_annotation_study_mapping_id_2dccb854; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_annotation_study_mapping_id_2dccb854 ON public.uploads_annotation USING btree (study_mapping_id);


--
-- Name: uploads_aud_actor_i_9de547_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_aud_actor_i_9de547_idx ON public.uploads_auditlog USING btree (actor_id);


--
-- Name: uploads_aud_event_t_1214c6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_aud_event_t_1214c6_idx ON public.uploads_auditlog USING btree (event_type);


--
-- Name: uploads_aud_occurre_2fca7b_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_aud_occurre_2fca7b_idx ON public.uploads_auditlog USING btree (occurred_at);


--
-- Name: uploads_aud_upload__083092_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_aud_upload__083092_idx ON public.uploads_auditlog USING btree (upload_job_id);


--
-- Name: uploads_auditlog_upload_job_id_7cbfae3b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_auditlog_upload_job_id_7cbfae3b ON public.uploads_auditlog USING btree (upload_job_id);


--
-- Name: uploads_chu_created_c31303_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_chu_created_c31303_idx ON public.uploads_chunkedupload USING btree (created_at);


--
-- Name: uploads_chu_expires_98439d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_chu_expires_98439d_idx ON public.uploads_chunkedupload USING btree (expires_at);


--
-- Name: uploads_chu_status_bc94f6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_chu_status_bc94f6_idx ON public.uploads_chunkedupload USING btree (status);


--
-- Name: uploads_chu_uploade_eb8861_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_chu_uploade_eb8861_idx ON public.uploads_chunkedupload USING btree (uploader_id);


--
-- Name: uploads_ima_orthanc_af10d9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ima_orthanc_af10d9_idx ON public.uploads_image USING btree (orthanc_instance_id);


--
-- Name: uploads_ima_sop_ins_3d71cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ima_sop_ins_3d71cf_idx ON public.uploads_image USING btree (sop_instance_uid);


--
-- Name: uploads_ima_study_m_70d4fd_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_ima_study_m_70d4fd_idx ON public.uploads_image USING btree (study_mapping_id);


--
-- Name: uploads_image_study_mapping_id_8de21a82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_image_study_mapping_id_8de21a82 ON public.uploads_image USING btree (study_mapping_id);


--
-- Name: uploads_pat_created_6e3754_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_pat_created_6e3754_idx ON public.uploads_patient USING btree (created_at);


--
-- Name: uploads_pat_pseudo__8bc026_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_pat_pseudo__8bc026_idx ON public.uploads_patient USING btree (pseudo_id);


--
-- Name: uploads_patient_pseudo_id_2ad29a4c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_patient_pseudo_id_2ad29a4c_like ON public.uploads_patient USING btree (pseudo_id varchar_pattern_ops);


--
-- Name: uploads_stu_acquisi_72ee6f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_stu_acquisi_72ee6f_idx ON public.uploads_studymapping USING btree (acquisition_date);


--
-- Name: uploads_stu_orthanc_44bfb0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_stu_orthanc_44bfb0_idx ON public.uploads_studymapping USING btree (orthanc_study_id);


--
-- Name: uploads_stu_patient_459797_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_stu_patient_459797_idx ON public.uploads_studymapping USING btree (patient_id);


--
-- Name: uploads_stu_pseudo__5093a1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_stu_pseudo__5093a1_idx ON public.uploads_studymapping USING btree (pseudo_study_uid);


--
-- Name: uploads_studymapping_patient_id_dcf22d78; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_studymapping_patient_id_dcf22d78 ON public.uploads_studymapping USING btree (patient_id);


--
-- Name: uploads_studymapping_pseudo_study_uid_265a033a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_studymapping_pseudo_study_uid_265a033a_like ON public.uploads_studymapping USING btree (pseudo_study_uid varchar_pattern_ops);


--
-- Name: uploads_studymapping_upload_job_id_6e162daa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_studymapping_upload_job_id_6e162daa ON public.uploads_studymapping USING btree (upload_job_id);


--
-- Name: uploads_upl_chunked_00d5dc_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_chunked_00d5dc_idx ON public.uploads_uploadchunk USING btree (chunked_upload_id, chunk_number);


--
-- Name: uploads_upl_status_2030b7_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_status_2030b7_idx ON public.uploads_uploadjob USING btree (status);


--
-- Name: uploads_upl_submitt_02eb93_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_submitt_02eb93_idx ON public.uploads_uploadjob USING btree (submitted_at);


--
-- Name: uploads_upl_uploade_6a1121_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_uploade_6a1121_idx ON public.uploads_uploadjob USING btree (uploader_id);


--
-- Name: uploads_upl_uploade_fa6e87_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_uploade_fa6e87_idx ON public.uploads_uploadchunk USING btree (uploaded_at);


--
-- Name: uploads_upl_verific_e76706_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_upl_verific_e76706_idx ON public.uploads_uploadchunk USING btree (verification_status);


--
-- Name: uploads_uploadchunk_chunked_upload_id_730d21a9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uploads_uploadchunk_chunked_upload_id_730d21a9 ON public.uploads_uploadchunk USING btree (chunked_upload_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_annotation uploads_annotation_study_mapping_id_2dccb854_fk_uploads_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_annotation
    ADD CONSTRAINT uploads_annotation_study_mapping_id_2dccb854_fk_uploads_s FOREIGN KEY (study_mapping_id) REFERENCES public.uploads_studymapping(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_auditlog uploads_auditlog_upload_job_id_7cbfae3b_fk_uploads_uploadjob_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_auditlog
    ADD CONSTRAINT uploads_auditlog_upload_job_id_7cbfae3b_fk_uploads_uploadjob_id FOREIGN KEY (upload_job_id) REFERENCES public.uploads_uploadjob(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_image uploads_image_study_mapping_id_8de21a82_fk_uploads_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_image
    ADD CONSTRAINT uploads_image_study_mapping_id_8de21a82_fk_uploads_s FOREIGN KEY (study_mapping_id) REFERENCES public.uploads_studymapping(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_studymapping uploads_studymapping_patient_id_dcf22d78_fk_uploads_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_studymapping
    ADD CONSTRAINT uploads_studymapping_patient_id_dcf22d78_fk_uploads_patient_id FOREIGN KEY (patient_id) REFERENCES public.uploads_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_studymapping uploads_studymapping_upload_job_id_6e162daa_fk_uploads_u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_studymapping
    ADD CONSTRAINT uploads_studymapping_upload_job_id_6e162daa_fk_uploads_u FOREIGN KEY (upload_job_id) REFERENCES public.uploads_uploadjob(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: uploads_uploadchunk uploads_uploadchunk_chunked_upload_id_730d21a9_fk_uploads_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uploads_uploadchunk
    ADD CONSTRAINT uploads_uploadchunk_chunked_upload_id_730d21a9_fk_uploads_c FOREIGN KEY (chunked_upload_id) REFERENCES public.uploads_chunkedupload(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict BIpTuvVNmzGFPMugSgYpeTYfLYwBdNv4jiDblPOFDzrDFHFQZSdh1C45lXGbCr5

