# Generated by Django 6.0.2 on 2026-02-26 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudo_id', models.CharField(help_text='De-identified patient identifier', max_length=64, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, null=True)),
                ('age_at_first_acquisition', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('cohort_tag', models.CharField(blank=True, help_text='Research cohort identifier', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pseudo_id'], name='uploads_pat_pseudo__8bc026_idx'), models.Index(fields=['created_at'], name='uploads_pat_created_6e3754_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_id', models.CharField(help_text='Identifier of the user who uploaded', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=16)),
                ('tar_temp_path', models.CharField(blank=True, help_text='Local temp directory path where tar is extracted', max_length=512)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manifest_raw', models.JSONField(blank=True, help_text='Original manifest JSON for audit trail', null=True)),
                ('error_report', models.JSONField(blank=True, help_text='Structured list of per-image errors and warnings', null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='uploads_upl_status_2030b7_idx'), models.Index(fields=['uploader_id'], name='uploads_upl_uploade_6a1121_idx'), models.Index(fields=['submitted_at'], name='uploads_upl_submitt_02eb93_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudo_study_uid', models.CharField(help_text='Pseudonymized DICOM Study Instance UID from manifest', max_length=256, unique=True)),
                ('orthanc_study_id', models.CharField(help_text='Orthanc internal UUID for this study', max_length=64)),
                ('acquisition_date', models.DateField(help_text='Date of image acquisition')),
                ('clinical_indication', models.TextField(blank=True, help_text='Clinical reason for imaging')),
                ('pathology_labels', models.JSONField(blank=True, default=list, help_text='List of known pathology labels')),
                ('contrast_used', models.BooleanField(default=False, help_text='Whether contrast agent was used')),
                ('contrast_agent', models.CharField(blank=True, help_text='Name of contrast agent used', max_length=128, null=True)),
                ('source_institution', models.CharField(blank=True, help_text='Source hospital or imaging center', max_length=128, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the study')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_mappings', to='uploads.patient')),
                ('upload_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_mappings', to='uploads.uploadjob')),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SUBMIT', 'Submit'), ('VALIDATE_OK', 'Validation OK'), ('VALIDATE_FAIL', 'Validation Failed'), ('IMAGE_PUSH_OK', 'Image Push OK'), ('IMAGE_PUSH_FAIL', 'Image Push Failed'), ('COMPLETE', 'Job Complete'), ('FAILED', 'Job Failed'), ('PARTIAL', 'Job Partial Success')], help_text='Type of event', max_length=64)),
                ('actor_id', models.CharField(help_text='Pseudonymized uploader/actor', max_length=128)),
                ('detail', models.JSONField(blank=True, help_text='Event-specific payload', null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('upload_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='uploads.uploadjob')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orthanc_instance_id', models.CharField(help_text='Orthanc instance UUID this annotation targets', max_length=256)),
                ('annotation_uid', models.CharField(help_text='Unique identifier for the annotation', max_length=256)),
                ('annotator_id', models.CharField(help_text='Identifier of the annotator', max_length=128)),
                ('annotation_date', models.DateField(blank=True, help_text='Date of annotation', null=True)),
                ('type', models.CharField(choices=[('SEGMENTATION', 'Segmentation'), ('BOUNDING_BOX', 'Bounding Box'), ('LANDMARK', 'Landmark'), ('CLASSIFICATION', 'Classification')], help_text='Type of annotation', max_length=16)),
                ('label', models.CharField(help_text='Label or description of annotation', max_length=256)),
                ('annotation_data', models.JSONField(blank=True, help_text='Inline annotation payload', null=True)),
                ('annotation_file', models.FileField(blank=True, help_text='Annotation file stored via Django FileStorage', null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='uploads.studymapping')),
            ],
            options={
                'ordering': ['annotation_date'],
                'indexes': [models.Index(fields=['study_mapping'], name='uploads_ann_study_m_18f71b_idx'), models.Index(fields=['annotation_uid'], name='uploads_ann_annotat_47d4ff_idx'), models.Index(fields=['annotator_id'], name='uploads_ann_annotat_ffc9ff_idx'), models.Index(fields=['orthanc_instance_id'], name='uploads_ann_orthanc_e14856_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studymapping',
            index=models.Index(fields=['pseudo_study_uid'], name='uploads_stu_pseudo__5093a1_idx'),
        ),
        migrations.AddIndex(
            model_name='studymapping',
            index=models.Index(fields=['patient'], name='uploads_stu_patient_459797_idx'),
        ),
        migrations.AddIndex(
            model_name='studymapping',
            index=models.Index(fields=['acquisition_date'], name='uploads_stu_acquisi_72ee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='studymapping',
            index=models.Index(fields=['orthanc_study_id'], name='uploads_stu_orthanc_44bfb0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['upload_job'], name='uploads_aud_upload__083092_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='uploads_aud_event_t_1214c6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_id'], name='uploads_aud_actor_i_9de547_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['occurred_at'], name='uploads_aud_occurre_2fca7b_idx'),
        ),
    ]
