# Generated by Django 6.0.2 on 2026-02-26 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_id', models.CharField(help_text='Identifier of the user uploading', max_length=128)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=16)),
                ('filename', models.CharField(help_text='Original filename of the uploaded file', max_length=512)),
                ('total_size', models.BigIntegerField(help_text='Total file size in bytes')),
                ('total_chunks', models.PositiveIntegerField(help_text='Total number of chunks')),
                ('uploaded_chunks', models.PositiveIntegerField(default=0, help_text='Number of chunks successfully uploaded')),
                ('chunk_size', models.PositiveIntegerField(default=10485760, help_text='Size of each chunk in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 hash of complete file for integrity verification', max_length=128, null=True)),
                ('temp_dir', models.CharField(help_text='Temporary directory path where chunks are stored', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when upload was completed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete incomplete uploads after this time', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploader_id'], name='uploads_chu_uploade_eb8861_idx'), models.Index(fields=['status'], name='uploads_chu_status_bc94f6_idx'), models.Index(fields=['created_at'], name='uploads_chu_created_c31303_idx'), models.Index(fields=['expires_at'], name='uploads_chu_expires_98439d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_number', models.PositiveIntegerField(help_text='Sequential chunk number (0-based)')),
                ('chunk_size', models.BigIntegerField(help_text='Actual size of this chunk in bytes')),
                ('chunk_hash', models.CharField(help_text='SHA256 hash of chunk for integrity verification', max_length=128)),
                ('file_path', models.CharField(help_text='Path to chunk file on disk', max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether chunk integrity has been verified')),
                ('chunked_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.chunkedupload')),
            ],
            options={
                'ordering': ['chunk_number'],
                'indexes': [models.Index(fields=['chunked_upload', 'chunk_number'], name='uploads_upl_chunked_00d5dc_idx'), models.Index(fields=['uploaded_at'], name='uploads_upl_uploade_fa6e87_idx')],
                'unique_together': {('chunked_upload', 'chunk_number')},
            },
        ),
    ]
