# Generated by Django 6.0.2 on 2026-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_auto_verification_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadchunk',
            new_name='uploads_upl_verific_e76706_idx',
            old_name='uploads_upl_verifi_idx',
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='anonymization_report',
            field=models.JSONField(blank=True, help_text='Report on GDPR anonymization and pseudo ID generation per image', null=True),
        ),
    ]
