# Generated by Django 6.0.2 on 2026-02-26 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_rename_uploads_upl_verifi_idx_uploads_upl_verific_e76706_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original DICOM filename', max_length=256)),
                ('orthanc_instance_id', models.CharField(blank=True, help_text='Orthanc SOPInstanceUID for this image', max_length=64, null=True)),
                ('sop_instance_uid', models.CharField(blank=True, help_text='DICOM SOPInstanceUID', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='uploads.studymapping')),
            ],
            options={
                'ordering': ['filename'],
                'indexes': [models.Index(fields=['study_mapping'], name='uploads_ima_study_m_70d4fd_idx'), models.Index(fields=['orthanc_instance_id'], name='uploads_ima_orthanc_af10d9_idx'), models.Index(fields=['sop_instance_uid'], name='uploads_ima_sop_ins_3d71cf_idx')],
            },
        ),
    ]
