# Generated by Django 6.0.2 on 2026-02-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymapping',
            name='orthanc_study_id',
            field=models.CharField(blank=True, help_text='Orthanc internal UUID for this study', max_length=64, null=True),
        ),
    ]
