# Generated by Django 6.0.5 on 2026-06-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0022_ctexamination_study_set_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ctexamination',
            name='contrast',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ctexamination',
            name='examination_group',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ctexamination',
            name='protocol_type',
            field=models.CharField(blank=True, choices=[('PEDIATRIC_HEAD', 'Pediatric Head'), ('PEDIATRIC_BODY', 'Pediatric Body'), ('YOUNG_ADULT', 'Young Adult')], max_length=32),
        ),
        migrations.AddField(
            model_name='ctexamination',
            name='rhythm_pseudo_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated RHYTHM repository pseudo-ID', max_length=64),
        ),
        migrations.CreateModel(
            name='RhythmPseudoIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='RHY-SITE-INDICATION-CONTRAST-GROUP prefix', max_length=64, unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['prefix'], name='uploads_rhy_prefix_a82960_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=256)),
                ('department', models.CharField(blank=True, max_length=256)),
                ('professional_role', models.CharField(choices=[('radiologist', 'Radiologist'), ('medical_physicist', 'Medical Physicist'), ('radiographer', 'Radiographer / CT Technologist'), ('pacs_it', 'PACS / IT Administrator'), ('research_coordinator', 'Research Coordinator'), ('principal_investigator', 'Principal Investigator'), ('dpo', 'Data Protection Officer'), ('other', 'Other: please specify')], max_length=64)),
                ('professional_role_other', models.CharField(blank=True, max_length=256)),
                ('site_code', models.CharField(blank=True, default='', max_length=16)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution'], name='uploads_use_institu_11a7e5_idx'), models.Index(fields=['site_code'], name='uploads_use_site_co_a432a8_idx')],
            },
        ),
    ]
