# Generated by Django 6.0.5 on 2026-07-13 07:53
#
# The AlterField below is state-only, matching the pattern established in
# 0024_alter_ctexamination_rhythm_pseudo_id: Django's autodetector re-flags
# this field on every makemigrations run (an internal representation
# difference between Django versions), but the DB column is already
# 'repository_study_id' and must not be renamed back to 'rhythm_pseudo_id'.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0028_userprofile_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rhythmpseudoidcounter',
            new_name='uploads_rhy_prefix_a82960_idx',
            old_name='uploads_rhyc_prefix_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='uploads_use_institu_11a7e5_idx',
            old_name='uploads_userprofile_inst_idx',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='ctexamination',
                    name='rhythm_pseudo_id',
                    field=models.CharField(blank=True, db_column='repository_study_id', db_index=True, help_text='Auto-generated RHYTHM repository pseudo-ID', max_length=64),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['site_code'], name='uploads_use_site_co_a432a8_idx'),
        ),
    ]
