# Generated by Django 6.0.7 on 2026-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0032_backfill_site_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='data_classification',
            field=models.CharField(blank=True, choices=[('anonymized', 'Anonymized data'), ('pseudonymized', 'Pseudonymized data')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_classification',
            field=models.CharField(blank=True, choices=[('anonymized', 'Anonymized data'), ('pseudonymized', 'Pseudonymized data')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_classification_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
